[package]
name = "spine_demos"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13"
bevy_spine = "0.9"
rand = "0.8"
strum = "0.24"
strum_macros = "0.24"

[profile.dev.package."*"]
opt-level = 3
