[package]
name = "spine_demos"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.8" }
rand = "0.8"
bevy_spine = { version = "0.3" }
strum = "0.24"
strum_macros = "0.24"

[profile.dev.package."*"]
opt-level = 3
